<?php
// Web対応セットアップスクリプト
// URLパラメータ:
// - setup.php: 通常の追加
// - setup.php?reset=1: 全削除してリセット
// - setup.php?add=名前: 1名だけ追加

header('Content-Type: text/html; charset=utf-8');
require_once 'lib/db.php';

$reset = isset($_GET['reset']) && $_GET['reset'] === '1';
$addOne = $_GET['add'] ?? '';

try {
  $pdo = db();
  
  echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Setup</title><style>body{font-family:monospace;white-space:pre-wrap;}</style></head><body>";
  echo "=== Kid Activity Tracker Web Setup ===\n\n";
  
  // リセット処理
  if ($reset) {
    echo "全データをリセットします...\n";
    $pdo->exec("DELETE FROM sessions");
    $pdo->exec("DELETE FROM kids");
    echo "✓ 全データを削除しました\n\n";
  }
  
  // 1名追加モード
  if ($addOne) {
    echo "「{$addOne}」を追加します...\n\n";
    $kids = [$addOne];
  } else {
    // config.phpから子供の名前を取得
    $config = require 'config.php';
    $kids = array_values($config['kids_setup'] ?? []);
    
    if (empty($kids)) {
      echo "エラー: config.phpに'kids_setup'配列を設定するか、?add=名前 で追加してください\n\n";
      echo "使用例:\n";
      echo "- setup.php?add=太郎\n";
      echo "- setup.php?reset=1 (全削除)\n";
      exit(1);
    }
  }
  
  // 既存データ表示
  $existing = $pdo->query("SELECT COUNT(*) as count FROM kids")->fetch();
  if ($existing['count'] > 0 && !$reset) {
    echo "現在の登録:\n";
    $stmt = $pdo->query("SELECT id, display_name FROM kids ORDER BY created_at");
    while ($row = $stmt->fetch()) {
      echo "  - {$row['display_name']}: {$row['id']}\n";
    }
    echo "\n";
  }
  
  echo "子供のデータを登録中...\n\n";
  
  foreach ($kids as $name) {
    // 既に同じ名前が存在するかチェック
    $stmt = $pdo->prepare("SELECT id FROM kids WHERE display_name = ? AND archived = 0");
    $stmt->execute([$name]);
    if ($stmt->fetch()) {
      echo "  - {$name}: 既に登録済みです（スキップ）\n";
      continue;
    }
    
    // 新規登録
    $id = uuid();
    $stmt = $pdo->prepare("INSERT INTO kids (id, display_name) VALUES (?, ?)");
    $stmt->execute([$id, $name]);
    
    echo "  - {$name}: {$id}\n";
  }
  
  echo "\n=== 登録完了 ===\n";
  
  // config.phpのkids配列を自動更新
  echo "config.phpのkids配列を自動更新中...\n";
  
  $config_path = 'config.php';
  if (file_exists($config_path)) {
    $config = require $config_path;
    
    // DBから最新のkids情報を取得してkids配列を更新
    $stmt = $pdo->query("SELECT id, display_name FROM kids WHERE archived = 0 ORDER BY created_at");
    $config['kids'] = [];
    while ($row = $stmt->fetch()) {
      $config['kids'][$row['id']] = $row['display_name'];
    }
    
    // kids_setup配列を削除（セキュリティのため）
    unset($config['kids_setup']);
    
    // config.phpに書き戻し
    $config_content = "<?php\n// Kid Activity Tracker Configuration\n// Auto-generated by setup.php\n\nreturn " . var_export($config, true) . ";\n";
    
    if (file_put_contents($config_path, $config_content)) {
      echo "✓ config.phpを自動更新しました\n";
      echo "✓ セキュリティのためkids_setup配列を削除しました\n";
    } else {
      echo "⚠ config.phpの更新に失敗しました（権限をご確認ください）\n";
    }
  } else {
    echo "⚠ config.phpが見つかりません\n";
  }
  
  echo "\n各子供専用のURL:\n";
  
  // 現在のドメインとパスを取得
  $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https://' : 'http://';
  $domain = $_SERVER['HTTP_HOST'];
  $script_path = dirname($_SERVER['SCRIPT_NAME']);
  $base_url = $protocol . $domain . $script_path;
  
  $stmt = $pdo->query("SELECT id, display_name FROM kids WHERE archived = 0 ORDER BY created_at");
  while ($row = $stmt->fetch()) {
    $kid_url = "?child={$row['id']}";
    $full_url = $base_url . "/" . $kid_url;
    echo "  - {$row['display_name']}: <a href=\"{$full_url}\" target=\"_blank\">{$kid_url}</a>\n";
  }
  
  echo "</body></html>";
  
} catch (Exception $e) {
  echo "エラーが発生しました: " . $e->getMessage() . "\n";
  echo "</body></html>";
  exit(1);
}